Repository IIM-Creative-Technology/nodejs-A4IWM2-042022, pull requests merged in 2022-04, with the labels that each got.

#2 npm and modules
  README.md
Labels: documentation

#11 DELETE idea
  .idea/workspace.xml
Labels: enhancement

#10 Update README, add cors resolution
  README.md
Labels: documentation

#24 Documentation Sequelize
  doc-sequelize/README.md
Labels: documentation

#28 Fix Cors section and the summary
  README.md
Labels: bug, documentation
